### ISSUE TITLE
does not include subdirectories with this cmd: es6-plato -r -d report src 

### ISSUE THREAD

**Issue by RonnieRen** [the-simian/es6-plato#47] opened 2018-03-19 03:33 UTC
anything wrong with my command line ?

**Comment by the-simian** [comment] 2018-03-19 20:17
@RonnieRen 
Offhand it looks right (possibly you night need to put a `.` after the `-r`, I can't recall atm)
- is it throwing any errors?
- does it only work one level deep, but does work just fine?
- can you post your cmd line output?

If you do these things can help more, I'll do my best to test this also.

oh yes, what is your environment osx/windows? bash/cygwin?

thanks for the issue! I appreciate it!

**Comment by RonnieRen** [comment] 2018-03-20 16:04
@the-simian 
thanks for your response.
* there is not any errors thrown
*  yes it only works one level deep.
* the output is only one word:
```
   $ ./node_modules/.bin/es6-plato -r -d ./report src
   Done!
```
BTW,  ```. ```(current directory) is not accepted as a valid command line after ``` -r ```

**Comment by the-simian** [comment] 2018-05-11 03:05
hey I just tested your exact command and I couldnt reproduce the issue, let me show you
![image](https://user-images.githubusercontent.com/954596/39904594-3b73ee76-549e-11e8-8dd4-b24203613bb4.png)

**Comment by the-simian** [comment] 2018-05-11 03:07
basically I just did a quick `yarn-add` es6-plato and ran the command you pasted and it got everything, you can see in other parts of the image its doing 1 level deep, 2 levels deep, etc.

Can you maybe make a small test project reproducing this? Its just not happening for me.

I'm closing this because its not happening for me, but I'll still keep looking at it if you can make me a project that definitely does the thing you describe.

**Closed as completed by the-simian** 2018-05-11 03:07 UTC
